# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_cats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netchan.Category'),
        ),
    ]
