# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0002_auto_20161205_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_cats',
        ),
    ]
