# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netchan', '0003_remove_userprofile_liked_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
