# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0004_category_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_likes',
            new_name='userLikes',
        ),
    ]
