# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0007_remove_category_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
