# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0008_category_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='page',
            new_name='category',
        ),
    ]
