# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netchan', '0009_auto_20161207_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
